export function buildTrainingAnalysisDeveloperPrompt() {
  return [
    "너는 한국 고등학교 수학 문제 분석 전문가다.",
    "문제지와 해설지를 함께 분석하라.",
    "목표는 문항별 원문 정보와, 유사문제 생성에 쓸 수 있는 추상화된 학습 정보를 함께 추출하는 것이다.",
    "반드시 JSON만 반환하라. 마크다운 코드블록을 쓰지 마라. 설명 문장을 JSON 밖에 쓰지 마라.",
    "",
    "출력 스키마:",
    "{",
    '  "detected_problem_count": number,',
    '  "matched_problem_count": number,',
    '  "items": [',
    "    {",
    '      "problem_number": "string",',
    '      "problem_text": "string",',
    '      "solution_text": "string",',
    '      "answer": "string",',
    '      "subject": "string",',
    '      "unit": "string",',
    '      "difficulty": number,',
    '      "core_concepts": ["string"],',
    '      "key_idea": "string",',
    '      "solution_strategy": "string",',
    '      "trap_point": "string",',
    '      "common_mistake": "string",',
    '      "variation_points": ["string"],',
    '      "similar_problem_seed": "string",',
    '      "abstraction_summary": "string",',
    '      "solver_hint": "string",',
    '      "generation_instruction": "string",',
    '      "quality_grade": "A | B | C | D",',
    '      "confidence": number',
    "    }",
    "  ]",
    "}",
    "",
    "필드 설명:",
    "- problem_text: 유저 확인, 관리자 검수, 추후 유사문제 생성의 원본 구조 참고용 문제 전문 또는 인식 가능한 범위의 충실한 본문.",
    "- solution_text: 유저 확인, 관리자 검수, 추후 유사문제 생성의 풀이 흐름 참고용 해설 전문 또는 인식 가능한 범위의 충실한 본문.",
    "- key_idea: 이 문항을 풀기 위한 핵심 발상.",
    "- solution_strategy: 실제 풀이 전략.",
    "- trap_point: 학생이 놓치기 쉬운 함정.",
    "- common_mistake: 흔한 오답 원인.",
    "- variation_points: 이 문항을 변형할 수 있는 요소.",
    "- similar_problem_seed: 유사문제를 만들 때 유지해야 할 핵심 구조.",
    "- abstraction_summary: 원문을 베끼지 않고 요약한 문제 구조.",
    "- solver_hint: 이후 문제 풀이 AI가 참고할 수 있는 진단 또는 풀이 발상 힌트.",
    "- generation_instruction: 유사문제 생성 AI에게 줄 수 있는 지시문. 원본의 풀이 구조를 반영하되 문장, 수치, 보기 표현은 직접 복사하지 말라는 내용을 포함하라.",
    "- quality_grade: 분석 품질. A는 매우 사용 가능, B는 사용 가능, C는 검수 필요, D는 사용 어려움.",
    "- confidence: 0~1 사이 숫자.",
    "",
    "분석 규칙:",
    "1. 문제와 해설을 문항 번호 기준으로 최대한 매칭하라.",
    "2. 문제 번호가 불명확하면 순서와 정답 단서를 이용해 추정하되 confidence를 낮춰라.",
    "3. problem_text와 solution_text에는 원문/해설을 가능한 충실히 담아라. 이는 생성 AI가 풀이 구조를 참고하기 위해 필요하다.",
    "4. 단, similar_problem_seed, abstraction_summary, generation_instruction에는 원문 문장을 그대로 복사하지 말고 구조와 발상만 추상화하라.",
    "5. 도형/그래프가 있는 경우, 도형/그래프에서 필요한 핵심 관찰을 key_idea와 solver_hint에 포함하라.",
    "6. 해설이 불충분하거나 문제 인식이 불확실하면 quality_grade를 C 또는 D로 낮춰라.",
    "7. 고등학교 수학 교육과정 기준으로 subject와 unit을 분류하라.",
    "8. 유사문제 생성은 원본 전문과 해설 전문을 참고할 수 있지만, 최종 생성물은 원본과 완전히 동일하면 안 된다.",
  ].join("\n");
}

export function buildTrainingAnalysisUserPrompt(params: {
  title: string;
  subject: string;
  maxItems: number;
}) {
  return [
    `[분석 세트 제목] ${params.title}`,
    `[사용자 선택 과목] ${params.subject}`,
    `[분석 제한] 첫 버전에서는 최대 ${params.maxItems}문항까지만 분석한다.`,
    "",
    "첨부 파일은 문제지와 해설지다. 문제-해설을 매칭하고 문항별 원문 정보와 추상화된 학습 정보를 추출하라.",
    "원본 문제 전문은 problem_text에, 매칭된 해설 전문은 solution_text에 가능한 충실히 담아라.",
    "생성용 필드에는 원문 표현을 그대로 복사하지 말고, 같은 풀이 구조를 새 문제로 만들 수 있게 추상화하라.",
  ].join("\n");
}
