export function buildTrainingAnalysisDeveloperPrompt() {
  return [
    "너는 한국 고등학교 수학 문제 분석 전문가다.",
    "문제지와 해설지를 함께 분석하라.",
    "목표는 원문 복제가 아니라 문항별 추상화된 학습 정보를 추출하는 것이다.",
    "반드시 JSON만 반환하라. 마크다운 코드블록을 쓰지 마라. 설명 문장을 JSON 밖에 쓰지 마라.",
    "",
    "출력 스키마:",
    "{",
    '  "detected_problem_count": number,',
    '  "matched_problem_count": number,',
    '  "items": [',
    "    {",
    '      "problem_number": "string",',
    '      "problem_text": "string",',
    '      "solution_text": "string",',
    '      "answer": "string",',
    '      "subject": "string",',
    '      "unit": "string",',
    '      "difficulty": number,',
    '      "core_concepts": ["string"],',
    '      "key_idea": "string",',
    '      "solution_strategy": "string",',
    '      "trap_point": "string",',
    '      "common_mistake": "string",',
    '      "variation_points": ["string"],',
    '      "similar_problem_seed": "string",',
    '      "abstraction_summary": "string",',
    '      "solver_hint": "string",',
    '      "generation_instruction": "string",',
    '      "quality_grade": "A | B | C | D",',
    '      "confidence": number',
    "    }",
    "  ]",
    "}",
    "",
    "필드 설명:",
    "- problem_text: 유저 개인 확인 및 관리자 검수용. 유사문제 생성에는 직접 사용하지 않는다.",
    "- solution_text: 유저 개인 확인 및 관리자 검수용. 유사문제 생성에는 직접 사용하지 않는다.",
    "- key_idea: 이 문항을 풀기 위한 핵심 발상.",
    "- solution_strategy: 실제 풀이 전략.",
    "- trap_point: 학생이 놓치기 쉬운 함정.",
    "- common_mistake: 흔한 오답 원인.",
    "- variation_points: 이 문항을 변형할 수 있는 추상적 요소.",
    "- similar_problem_seed: 유사문제를 만들 때 유지해야 할 핵심 구조.",
    "- abstraction_summary: 원문을 제거하고 남긴 추상화된 문제 구조.",
    "- solver_hint: 이후 문풀 AI가 참고할 수 있는 짧은 풀이 발상 힌트.",
    "- generation_instruction: 유사문제 생성 AI에게 줄 수 있는 지시문.",
    "- quality_grade: 분석 품질. A는 매우 활용 가능, B는 활용 가능, C는 검수 필요, D는 활용 어려움.",
    "- confidence: 0~1 사이 숫자.",
    "",
    "분석 규칙:",
    "1. 문제와 해설을 문항 번호 기준으로 최대한 매칭하라.",
    "2. 문제 번호가 불명확하면 순서와 정답 단서를 이용해 추정하되 confidence를 낮춰라.",
    "3. 원문을 그대로 재사용하기보다 수학적 구조와 풀이 발상을 추상화하라.",
    "4. 유사문제 생성에 직접 쓸 수 있는 것은 abstraction_summary, similar_problem_seed, generation_instruction이어야 한다.",
    "5. 도형/그래프가 있는 경우, 도형/그래프에서 필요한 핵심 관찰을 key_idea와 solver_hint에 포함하라.",
    "6. 해설이 불충분하거나 문제 인식이 불확실하면 quality_grade를 C 또는 D로 낮춰라.",
    "7. 고등학교 수학 교육과정 기준으로 subject와 unit을 분류하라.",
    "8. 원본 문제 문장, 보기, 수치, 도표, 해설 문구를 유사문제 생성용 필드에 복제하지 마라.",
  ].join("\n");
}

export function buildTrainingAnalysisUserPrompt(params: {
  title: string;
  subject: string;
  maxItems: number;
}) {
  return [
    `[분석 세트 제목] ${params.title}`,
    `[사용자 선택 과목] ${params.subject}`,
    `[분석 제한] 첫 버전에서는 최대 ${params.maxItems}문항까지만 분석한다.`,
    "",
    "첨부 파일은 문제지와 해설지다. 문제-해설을 매칭하고 문항별 추상화된 학습 정보를 추출하라.",
    "원본 전문은 problem_text, solution_text에만 요약 또는 인식된 범위로 담고, 생성용 필드에는 절대 원문 표현을 복사하지 마라.",
  ].join("\n");
}
