import type { ChatGptProblemJson } from "@/lib/problem-bank/types";

export const problemBankImportStandardExample: ChatGptProblemJson[] = [
  {
    problem_code: "26xxx-xxxxA",
    base_problem_code: "26xxx-xxxx",
    variant_code: "A",
    code_system: "ebs",
    ebs_original_code: "26xxx-xxxx",
    source: "2027 수능특강 미적분",
    source_type: "ebs_special",
    exam_year: 2027,
    exam_month: null,
    problem_number: null,
    subject: "미적분",
    unit: "07. 정적분의 활용",
    level: "Level 2",
    original_ref: "07단원 Level 2 예제",
    internal_code: null,
    question_type: "multiple_choice",
    question_latex: "\\int_0^2 (3x^2-2x)\\,dx의 값은?",
    choices_json: ["1", "2", "3", "4", "5"],
    answer_json: {
      type: "choice",
      answer: 4,
    },
    solution_latex: "\\int_0^2 (3x^2-2x)\\,dx=[x^3-x^2]_0^2=8-4=4이므로 정답은 ④이다.",
    difficulty: 6,
    variant_strength: 2,
    tags: ["정적분", "다항함수", "계산"],
    has_graph: false,
    graph_json: null,
    layout_json: {
      estimated_height: "short",
      recommended_columns: 1,
      keep_choices_together: true,
    },
    visibility: "private",
    price_dak: 0,
  },
  {
    problem_code: "270630A",
    base_problem_code: "270630",
    variant_code: "A",
    code_system: "kice",
    source: "2027학년도 6월 모의평가",
    source_type: "mock",
    exam_year: 2027,
    exam_month: 6,
    problem_number: 30,
    subject: "미적분",
    unit: "도함수의 활용",
    level: "고난도",
    original_ref: "미적분 30번",
    ebs_original_code: null,
    internal_code: null,
    question_type: "multiple_choice",
    question_latex: "함수 f(x)=x^3-3x에 대하여 f'(a)=9일 때, 양수 a의 값은?",
    choices_json: ["\\sqrt{2}", "2", "\\sqrt{3}", "3", "4"],
    answer_json: {
      type: "choice",
      answer: 2,
    },
    solution_latex: "f'(x)=3x^2-3이다. f'(a)=9에서 3a^2-3=9, a^2=4이므로 양수 a=2이다.",
    difficulty: 8,
    variant_strength: 3,
    tags: ["도함수", "방정식", "모의평가"],
    has_graph: false,
    graph_json: null,
    layout_json: {
      estimated_height: "short",
      recommended_columns: 1,
      keep_choices_together: true,
    },
    visibility: "private",
    price_dak: 0,
  },
  {
    problem_code: "260525A",
    base_problem_code: "260525",
    variant_code: "A",
    code_system: "school_exam",
    source: "2026년 5월 학력평가",
    source_type: "school_exam",
    exam_year: 2026,
    exam_month: 5,
    problem_number: 25,
    subject: "미적분",
    unit: "수열의 극한",
    level: "중상",
    original_ref: "미적분 25번",
    ebs_original_code: null,
    internal_code: null,
    question_type: "multiple_choice",
    question_latex: "\\lim_{n\\to\\infty}\\frac{2n^2+1}{n^2+n}의 값은?",
    choices_json: ["0", "1", "2", "3", "4"],
    answer_json: {
      type: "choice",
      answer: 3,
    },
    solution_latex: "분자와 분모를 n^2으로 나누면 \\frac{2+1/n^2}{1+1/n}\\to 2이므로 정답은 ③이다.",
    difficulty: 5,
    variant_strength: 2,
    tags: ["극한", "수열", "학력평가"],
    has_graph: false,
    graph_json: null,
    layout_json: {
      estimated_height: "short",
      recommended_columns: 1,
      keep_choices_together: true,
    },
    visibility: "private",
    price_dak: 0,
  },
];

export const problemBankImportStandardJson = JSON.stringify(problemBankImportStandardExample, null, 2);
