import type {
  ExamBlueprint,
  GeneratedExamFile,
  GenerationStep,
  ReferenceAnalysisResult,
  ReferenceFile,
  ReferenceFileKind,
} from "./types";

export const referenceFileKinds: ReferenceFileKind[] = [
  "수능특강",
  "수능완성",
  "평가원/교육청 기출",
  "학교 기출",
  "학교 프린트",
  "직접 제작 자료",
];

export const mockReferenceFiles: ReferenceFile[] = [];

export const mockAnalysisResult: ReferenceAnalysisResult = {
  detectedSubject: "수학Ⅰ",
  majorUnits: ["지수와 로그", "지수함수와 로그함수"],
  detectedProblemCount: 22,
  majorTypes: ["그래프 해석", "조건 추론", "계산형", "서술형 증명"],
  examPoints: [
    "로그함수 그래프의 평행이동과 정의역 조건을 함께 묻는 문항 비중이 높습니다.",
    "단순 계산보다 조건 해석 후 방정식으로 환원하는 2단계 풀이가 자주 등장합니다.",
    "서술형은 풀이 과정의 논리 연결과 정의역 검토를 배점 요소로 둘 수 있습니다.",
  ],
  difficultyDistribution: {
    기본: 5,
    중간: 9,
    상: 6,
    고난도: 2,
  },
  transformablePoints: [
    "그래프 위치 관계를 새 함수 조건으로 재구성",
    "수치 대입형을 매개변수 조건형으로 변형",
    "객관식 선지 함정을 정의역 누락 또는 밑 조건으로 재설계",
  ],
  sourceRange: "지수법칙부터 로그함수의 그래프 활용까지",
};

export const mockExamBlueprint: ExamBlueprint = {
  title: "송도고형 수학Ⅰ 1학기 중간 예상기출",
  subject: "수학Ⅰ",
  totalProblems: 6,
  multipleChoiceCount: 4,
  writtenCount: 2,
  overallDifficulty: "상",
  overallTransformStrength: "높음",
  examMinutes: 50,
  sourceRange: mockAnalysisResult.sourceRange,
  referenceSummary: "업로드 참고 자료 기반 mock 분석",
  items: [
    {
      id: "item-1",
      number: 1,
      format: "객관식",
      referenceLocation: "업로드 자료 1번",
      topic: "지수법칙 계산",
      problemType: "계산형",
      score: 3.0,
      difficulty: "기본",
      transformStrength: "중간",
      intent: "지수법칙과 밑 조건을 정확히 적용하는지 확인합니다.",
    },
    {
      id: "item-2",
      number: 2,
      format: "객관식",
      referenceLocation: "업로드 자료 2번",
      topic: "로그의 성질",
      problemType: "조건 추론",
      score: 3.5,
      difficulty: "중간",
      transformStrength: "높음",
      intent: "로그식 변형 과정에서 정의역을 함께 점검하게 합니다.",
    },
    {
      id: "item-3",
      number: 3,
      format: "객관식",
      referenceLocation: "업로드 자료 3번",
      topic: "로그함수 그래프",
      problemType: "그래프 해석",
      score: 4.0,
      difficulty: "상",
      transformStrength: "높음",
      intent: "그래프의 평행이동과 교점 조건을 결합해 해석하도록 합니다.",
    },
    {
      id: "item-4",
      number: 4,
      format: "객관식",
      referenceLocation: "업로드 자료 4번",
      topic: "지수함수와 방정식",
      problemType: "복합 계산",
      score: 4.5,
      difficulty: "상",
      transformStrength: "중간",
      intent: "지수함수의 단조성을 이용해 방정식의 해를 판단합니다.",
    },
    {
      id: "item-5",
      number: 5,
      format: "서술형",
      referenceLocation: "업로드 자료 5번",
      topic: "로그함수의 최대최소",
      problemType: "서술형",
      score: 6.5,
      difficulty: "상",
      transformStrength: "높음",
      intent: "정의역 설정, 치환, 최댓값 판단 과정을 단계별로 평가합니다.",
    },
    {
      id: "item-6",
      number: 6,
      format: "서술형",
      referenceLocation: "업로드 자료 6번",
      topic: "로그함수와 매개변수",
      problemType: "고난도 추론",
      score: 7.0,
      difficulty: "고난도",
      transformStrength: "높음",
      intent: "매개변수 조건을 구간별로 나누어 논증하는 능력을 평가합니다.",
    },
  ],
};

export const generationSteps: GenerationStep[] = [
  { id: "validate", label: "출제 설계표 검증" },
  { id: "draft", label: "문항 초안 생성" },
  { id: "solution", label: "정답 및 해설 생성" },
  { id: "check", label: "문항별 검산" },
  { id: "similarity", label: "유사도 위험 검사" },
  { id: "exam-layout", label: "시험지 조판" },
  { id: "answer-layout", label: "답안지 조판" },
  { id: "analysis", label: "출제 분석표 생성" },
  { id: "export", label: "PDF/DOCX 변환" },
];

export const mockGeneratedFiles: GeneratedExamFile[] = [
  { id: "exam-docx", label: "시험지 원문", format: "DOCX", href: "#" },
  { id: "exam-pdf", label: "시험지 원문", format: "PDF", href: "#" },
  { id: "solution-docx", label: "정답 및 해설지", format: "DOCX", href: "#" },
  { id: "solution-pdf", label: "정답 및 해설지", format: "PDF", href: "#" },
  { id: "analysis-docx", label: "출제 분석표", format: "DOCX", href: "#" },
  { id: "analysis-pdf", label: "출제 분석표", format: "PDF", href: "#" },
];
