import type {
  AnalysisProblem,
  PracticeProblem,
} from "@/lib/juneMockAnalysis";

const officialSourceUrl =
  "https://cdn.kice.re.kr/suneung27mo06/index.html";

export const JUNE_MOCK_ANALYSIS_CONTENT: AnalysisProblem[] = [
  {
    id: "common-21",
    subject: "공통",
    number: 21,
    title: "최댓값으로 정의된 함수와 불연속",
    summary:
      "삼차함수의 역상 중 최댓값을 택하는 함수의 불연속 조건을 분석합니다.",
    concepts: ["삼차함수", "극값", "불연속", "역상"],
    difficulty: 4.5,
    status: "published",
    analysisUrl: "/analysis/2027-june-mock/common-21",
    practiceUrl: "/analysis/2027-june-mock/common-21/practice",
    officialSourceUrl,
    sourceLocation: "수학 영역 공통과목 21번",
    originalAnswer: "11",
    overview: [
      String.raw`최고차항의 계수가 1인 삼차함수를 $f(x) = x^3 + ax^2 + bx + c$로 놓습니다.`,
      String.raw`주어진 식의 오른쪽을 $H(t) = f'(t) - 4t^2 + 4$라고 두면 $H(t)$는 아래로 볼록한 이차함수입니다.`,
      String.raw`$g(t)$는 방정식 $f(\alpha) = H(t)$를 만족시키는 실수 $\alpha$ 중 가장 큰 값을 택합니다.`,
      String.raw`$g(t)$가 불연속이 되는 지점은 $H(t)$가 삼차함수 $f$의 극솟값에 닿는 순간과 연결됩니다.`,
    ],
    keyIdeas: [
      String.raw`$g(t)$가 $t = 3$에서만 불연속이라는 조건을 $H(t)$의 꼭짓점 조건으로 해석합니다.`,
      String.raw`$g(3) = 1$이므로 $x = 1$에서 $f$가 극솟값을 갖는다고 판단합니다.`,
      String.raw`$H(t)$의 꼭짓점이 $t = 3$에 있다는 조건과 $f'(1) = 0$을 함께 이용합니다.`,
      String.raw`마지막으로 $H(3) = f(1)$을 이용하여 상수항을 결정합니다.`,
    ],
    solutionSteps: [
      String.raw`$f(x) = x^3 + ax^2 + bx + c$로 놓으면 $f'(t) = 3t^2 + 2at + b$입니다.`,
      String.raw`따라서 $H(t) = f'(t) - 4t^2 + 4 = -t^2 + 2at + b + 4$입니다.`,
      String.raw`$H(t)$는 아래로 볼록한 이차함수이고, $g(t)$가 $t = 3$에서만 불연속이므로 $H(t)$의 꼭짓점의 $t$좌표는 3입니다.`,
      String.raw`$H(t)$의 꼭짓점의 $t$좌표는 $a$이므로 $a = 3$입니다.`,
      String.raw`$g(3) = 1$이므로 $x = 1$에서 $f$가 극솟값을 갖습니다. 따라서 $f'(1) = 0$입니다.`,
      String.raw`$f'(1) = 3 + 2a + b = 0$이고 $a = 3$이므로 $b = -9$입니다.`,
      String.raw`$H(3) = -9 + 18 - 9 + 4 = 4$입니다.`,
      String.raw`불연속이 발생하는 순간 $H(3) = f(1)$이므로 $f(1) = 4$입니다.`,
      String.raw`$f(1) = 1 + 3 - 9 + c = c - 5$이므로 $c = 9$입니다.`,
      String.raw`따라서 $f(x) = x^3 + 3x^2 - 9x + 9$입니다.`,
      String.raw`$f(2) = 8 + 12 - 18 + 9 = 11$입니다.`,
    ],
    commonMistakes: [
      String.raw`$g(t)$를 일반적인 역함수라고 생각하는 실수: $g(t)$는 모든 역상 중 최댓값만 택하므로 가지가 바뀌는 순간을 살펴야 합니다.`,
      "삼차함수의 극댓값과 극솟값을 구분하지 않는 실수: 가장 큰 해를 택하는 함수의 점프는 극솟값과 연결됩니다.",
      String.raw`$g(3) = 1$만으로 $f(1) = H(3)$만 사용하고 $f'(1) = 0$을 빠뜨리는 실수입니다.`,
      String.raw`$H(t)$의 꼭짓점 조건을 활용하지 않고 계수를 모두 직접 맞추려는 실수입니다.`,
    ],
  },
  {
    id: "common-22",
    subject: "공통",
    number: 22,
    title: "귀납적으로 정의된 수열의 경우 분류",
    summary:
      "출발점과 증가량을 구분하여 목표값에 도달하는 경로를 체계적으로 셉니다.",
    concepts: ["수열", "경우 분류", "경로 해석"],
    difficulty: 4.5,
    status: "published",
    analysisUrl: "/analysis/2027-june-mock/common-22",
    practiceUrl: "/analysis/2027-june-mock/common-22/practice",
    featured: true,
    officialSourceUrl,
    sourceLocation: "수학 영역 공통과목 22번",
    originalAnswer: "32",
    overview: [
      "이 문항은 귀납적으로 정의된 수열에서 특정 값을 갖는 항의 개수를 구하는 문제입니다.",
      String.raw`첨자 $n$에서 출발하면 $n \to 2n$, $n \to 4n + 1$, $n \to 4n + 3$의 세 가지 이동이 가능합니다.`,
      String.raw`$n \to 2n$에서는 수열의 값이 1 증가하고, $n \to 4n + 1$ 또는 $n \to 4n + 3$에서는 수열의 값이 4 증가합니다.`,
      String.raw`수열의 항을 앞에서부터 직접 계산하기보다 초기값 $a_1 = 1$과 $a_3 = 4$에서 목표값 10까지 도달하는 경로를 세는 것이 핵심입니다.`,
    ],
    keyIdeas: [
      String.raw`출발 가능한 경우를 $a_1 = 1$과 $a_3 = 4$로 분리합니다.`,
      "값이 1 증가하는 이동과 값이 4 증가하는 이동의 횟수를 구분합니다.",
      "증가량의 배열 순서를 계산합니다.",
      String.raw`값이 4 증가하는 이동은 첨자가 $4n + 1$ 또는 $4n + 3$으로 갈라지므로, 단계별 선택지의 수도 별도로 반영합니다.`,
      "서로 다른 이동 경로가 같은 첨자로 합쳐지지 않는지 역추적으로 검산합니다.",
    ],
    solutionSteps: [
      String.raw`$a_1 = 1$에서 시작하는 경우를 계산합니다. 목표값 10까지 총 9만큼 증가해야 합니다. 값이 1 증가하는 이동의 횟수를 $x$, 값이 4 증가하는 이동의 횟수를 $y$라고 하면 $x + 4y = 9$입니다.`,
      String.raw`가능한 경우는 $(x, y) = (9, 0), (5, 1), (1, 2)$입니다.`,
      String.raw`$(9, 0)$인 경우는 1가지입니다.`,
      String.raw`$(5, 1)$인 경우에는 총 6번의 이동 중 4 증가 이동의 위치를 고르는 방법이 6가지이고, 해당 이동의 갈래가 2가지이므로 $6 \times 2 = 12$가지입니다.`,
      String.raw`$(1, 2)$인 경우에는 총 3번의 이동 중 4 증가 이동의 위치를 고르는 방법이 3가지이고, 두 번의 4 증가 이동마다 갈래가 2가지이므로 $3 \times 2^2 = 12$가지입니다.`,
      String.raw`따라서 $a_1 = 1$에서 출발하는 경우는 $1 + 12 + 12 = 25$가지입니다.`,
      String.raw`$a_3 = 4$에서 시작하는 경우에는 목표값 10까지 총 6만큼 증가해야 하므로 $x + 4y = 6$입니다.`,
      String.raw`가능한 경우는 $(x, y) = (6, 0), (2, 1)$입니다.`,
      String.raw`$(6, 0)$인 경우는 1가지이고, $(2, 1)$인 경우는 총 3번의 이동 중 4 증가 이동의 위치를 고르는 방법 3가지와 갈래 2가지를 곱하여 $3 \times 2 = 6$가지입니다.`,
      String.raw`따라서 $a_3 = 4$에서 출발하는 경우는 $1 + 6 = 7$가지입니다.`,
      String.raw`두 출발점에서 얻은 경우를 더하면 $25 + 7 = 32$입니다.`,
      String.raw`따라서 $a_k = 10$을 만족시키는 자연수 $k$의 개수는 32입니다.`,
    ],
    commonMistakes: [
      String.raw`이동 순서만 세고 갈래 선택을 빠뜨리는 실수: 값이 4 증가하는 이동을 $y$번 사용하면 갈래 선택에 의한 $2^y$를 곱해야 합니다.`,
      String.raw`$a_1 = 1$에서 출발하는 경우만 계산하는 실수: 초기값으로 $a_3 = 4$도 주어졌으므로 두 출발점을 분리해야 합니다.`,
      "증가량의 배열 순서를 누락하는 실수: 같은 증가량 조합이라도 이동 순서가 다르면 서로 다른 첨자가 만들어집니다.",
      "서로 다른 경로가 같은 첨자로 이어질 수 있다고 생각하는 실수: 각 자연수 첨자는 이전 첨자를 역으로 추적했을 때 경로가 하나로 결정됩니다.",
    ],
  },
  {
    id: "probability-28",
    subject: "확률과 통계",
    number: 28,
    title: "카드 뒤집기 시행과 상태 전이",
    summary:
      "카드의 앞뒷면 상태를 집합으로 표현하고 반복 시행의 경우를 체계적으로 셉니다.",
    concepts: ["확률", "경우의 수", "상태 전이", "대칭차"],
    difficulty: 4.2,
    status: "published",
    analysisUrl: "/analysis/2027-june-mock/probability-28",
    practiceUrl: "/analysis/2027-june-mock/probability-28/practice",
    officialSourceUrl,
    sourceLocation: "수학 영역 확률과 통계 28번",
    originalAnswer: String.raw`$\frac{10}{81}$`,
    overview: [
      "각 카드가 앞면인지 뒷면인지 하나씩 추적하면 경우가 복잡해집니다.",
      "뒷면이 보이는 카드의 번호를 집합으로 표현하면, 카드를 뒤집는 시행은 집합의 대칭차로 나타낼 수 있습니다.",
      String.raw`처음에는 1번 카드와 6번 카드가 뒷면이므로 초기 상태는 $\{1, 6\}$입니다.`,
      String.raw`네 번의 시행을 마친 뒤 모든 카드가 앞면이 되려면, 네 번의 뒤집기 집합을 합성한 결과가 초기 상태 $\{1, 6\}$과 같아야 합니다.`,
    ],
    keyIdeas: [
      "카드 상태를 뒷면 카드 번호의 집합으로 표현합니다.",
      "같은 카드를 두 번 뒤집으면 원래 상태로 돌아오므로 집합의 대칭차 또는 XOR 연산을 사용합니다.",
      String.raw`주사위 눈 $k$에 따른 뒤집기 집합을 먼저 정리합니다.`,
      "반복 횟수가 네 번이므로 두 번 시행의 결과를 먼저 세고, 두 묶음을 결합하면 계산이 간결해집니다.",
    ],
    solutionSteps: [
      String.raw`주사위 눈에 따른 뒤집기 집합을 $A_k$라고 둡니다.`,
      String.raw`$A_1 = \{1\}$, $A_2 = \{2,3,4,5,6\}$, $A_3 = \{1,2,3\}$, $A_4 = \{4,5,6\}$, $A_5 = \{1,2,3,4,5\}$, $A_6 = \{6\}$입니다.`,
      String.raw`처음 뒷면인 카드의 집합은 $T = \{1, 6\}$입니다.`,
      "두 번 시행한 결과를 대칭차 기준으로 세면 가능한 상태는 여덟 종류입니다.",
      "아무 카드도 뒤집히지 않은 상태와 모든 카드가 뒤집힌 상태는 각각 6가지 순서로 만들어집니다.",
      "나머지 여섯 상태는 각각 4가지 순서로 만들어집니다.",
      "네 번의 시행을 두 번씩 두 묶음으로 나눕니다.",
      String.raw`두 묶음의 대칭차가 $T = \{1, 6\}$이 되도록 결합되는 순서의 수를 모두 더하면 160입니다.`,
      String.raw`전체 시행 결과의 수는 $6^4 = 1296$입니다.`,
      String.raw`따라서 확률은 $\frac{160}{1296} = \frac{10}{81}$입니다.`,
    ],
    commonMistakes: [
      "각 카드가 앞면이 될 확률을 독립적으로 곱하는 실수: 한 번의 시행에서 여러 카드가 동시에 뒤집히므로 독립이 아닙니다.",
      "같은 카드를 두 번 뒤집으면 다시 앞면이 된다는 점을 놓치는 실수입니다.",
      "처음부터 모든 카드가 앞면이라고 생각하는 실수: 초기 상태에는 1번과 6번 카드가 뒷면입니다.",
      "주사위 눈의 순서를 무시하는 실수: 같은 뒤집기 집합 조합이라도 나온 순서가 다르면 서로 다른 시행 결과입니다.",
    ],
  },
  {
    id: "calculus-28",
    subject: "미적분",
    number: 28,
    title: "합성 관계의 미분과 극한",
    summary:
      "지수함수의 교점에서 정의된 함수를 관계식으로 바꾸고 미분하여 극한을 계산합니다.",
    concepts: ["지수함수", "음함수 미분", "극한", "이계도함수"],
    difficulty: 4.3,
    status: "published",
    analysisUrl: "/analysis/2027-june-mock/calculus-28",
    practiceUrl: "/analysis/2027-june-mock/calculus-28/practice",
    officialSourceUrl,
    sourceLocation: "수학 영역 미적분 28번",
    originalAnswer: "5",
    overview: [
      String.raw`직선 $y = t$와 두 지수함수 곡선의 교점을 이용하여 $f(t)$, $g(t)$가 정의됩니다.`,
      "교점의 x좌표를 직접 구하려 하면 계산이 복잡해집니다.",
      String.raw`$f(t)$ 자체를 하나의 새로운 변수로 보고 $t$와 $f(t)$의 관계식을 만들면 간결하게 해결할 수 있습니다.`,
      String.raw`분자의 값이 $t = 1$에서 0이 되므로 이계도함수까지 계산해야 합니다.`,
    ],
    keyIdeas: [
      String.raw`점 $P$의 x좌표를 직접 구하지 않고 $f(t) = e^{2x_P}$로 놓습니다.`,
      String.raw`원래 곡선의 식을 이용하여 $t = f(t) - \frac{1}{\sqrt{f(t)}} + 1$이라는 관계식을 얻습니다.`,
      String.raw`점 $Q$에서는 $e^{2x_Q} = t$이므로 $g(t) = t - \frac{1}{\sqrt{t}} + 1$입니다.`,
      "분자와 분모가 모두 0으로 가므로 미분 또는 일차 근사를 이용하여 극한을 계산합니다.",
    ],
    solutionSteps: [
      String.raw`점 $P$의 x좌표를 $x_P$라고 하면 $f(t) = e^{2x_P}$입니다.`,
      String.raw`점 $P$는 곡선 $y = e^{2x} - e^{-x} + 1$ 위에 있으므로 $t = e^{2x_P} - e^{-x_P} + 1$입니다.`,
      String.raw`$e^{-x_P} = \frac{1}{\sqrt{f(t)}}$이므로 $t = f(t) - \frac{1}{\sqrt{f(t)}} + 1$입니다.`,
      String.raw`양변을 미분하면 $1 = f'(t)\left(1 + \frac{1}{2(f(t))^{3/2}}\right)$입니다.`,
      String.raw`$t = 1$일 때 $f(1) = 1$이므로 $f'(1) = \frac{2}{3}$입니다.`,
      String.raw`한 번 더 미분하면 $f''(1) = \frac{2}{9}$입니다.`,
      String.raw`점 $Q$의 x좌표를 $x_Q$라고 하면 $e^{2x_Q} = t$입니다.`,
      String.raw`따라서 $g(t) = e^{2x_Q} - e^{-x_Q} + 1 = t - \frac{1}{\sqrt{t}} + 1$입니다.`,
      String.raw`$g'(1) = \frac{3}{2}$이고 $g''(1) = -\frac{3}{4}$입니다.`,
      String.raw`$9f'(1) - 4g'(1) = 9 \times \frac{2}{3} - 4 \times \frac{3}{2} = 0$입니다.`,
      String.raw`따라서 구하려는 극한은 $9f''(1) - 4g''(1)$입니다.`,
      String.raw`$9 \times \frac{2}{9} - 4 \times \left(-\frac{3}{4}\right) = 2 + 3 = 5$입니다.`,
    ],
    commonMistakes: [
      String.raw`교점 $P$의 x좌표를 로그로 직접 풀려고 하는 실수: $f(t)$를 이용해 관계식을 만드는 편이 훨씬 간결합니다.`,
      String.raw`$f(t)$와 $g(t)$를 같은 식으로 착각하는 실수: 두 함수는 서로 다른 곡선의 세로 이동 결과입니다.`,
      String.raw`분자에 단순히 $t = 1$을 대입한 뒤 $\frac{0}{0}$에서 멈추는 실수입니다.`,
      "이계도함수 계산에서 음의 지수와 부호를 빠뜨리는 실수입니다.",
    ],
  },
  {
    id: "geometry-28",
    subject: "기하",
    number: 28,
    title: "초점을 지나는 현과 타원의 성질",
    summary:
      "초점에서 두 점까지의 거리비와 삼각형의 넓이를 이용하여 타원의 장축과 단축을 추적합니다.",
    concepts: ["타원", "초점", "거리비", "넓이"],
    difficulty: 4.4,
    status: "published",
    analysisUrl: "/analysis/2027-june-mock/geometry-28",
    practiceUrl: "/analysis/2027-june-mock/geometry-28/practice",
    officialSourceUrl,
    sourceLocation: "수학 영역 기하 28번",
    originalAnswer: "8",
    overview: [
      String.raw`타원의 두 초점을 $F(c, 0)$, $F'(-c, 0)$라고 둡니다.`,
      String.raw`점 $F$가 선분 $PQ$ 위에 있으므로 $P$와 $Q$는 초점 $F$를 기준으로 서로 반대 방향에 있습니다.`,
      String.raw`$\overline{PF}$와 $\overline{QF}$의 거리비를 이용하면 초점에서 바라본 방향의 코사인 값을 $\frac{a}{c}$로 표현할 수 있습니다.`,
      String.raw`삼각형 $FF'Q$의 넓이는 밑변 $\overline{FF'} = 2c$와 점 $Q$의 y좌표를 이용하여 계산합니다.`,
    ],
    keyIdeas: [
      String.raw`$p = \overline{PF}$, $q = \overline{QF}$로 놓고 주어진 거리비를 먼저 정리합니다.`,
      String.raw`점 $F$에서 점 $P$를 바라보는 방향과 x축이 이루는 각을 $\theta$라고 둡니다.`,
      String.raw`초점에서 타원 위의 점까지의 거리 공식 $p = \frac{b^2}{a + c\cos\theta}$, $q = \frac{b^2}{a - c\cos\theta}$를 활용합니다.`,
      String.raw`$\frac{q}{p}$의 값을 이용하여 $\cos\theta$를 $\frac{a}{c}$로 표현합니다.`,
      String.raw`삼각형의 넓이 조건을 이용하여 $c^2$을 구한 뒤 $b^2 = a^2 - c^2$을 계산합니다.`,
    ],
    solutionSteps: [
      String.raw`$p = \overline{PF}$, $q = \overline{QF}$로 놓습니다.`,
      String.raw`$\frac{\overline{PF}}{\overline{QF}} = \frac{1}{2}$이므로 $q = 2p$입니다.`,
      String.raw`$\frac{\overline{PF}}{\overline{FF'}} = \frac{\sqrt{6}}{16}$이고 $\overline{FF'} = 2c$이므로 $p = \frac{c\sqrt{6}}{8}$입니다.`,
      String.raw`따라서 $q = \frac{c\sqrt{6}}{4}$입니다.`,
      String.raw`점 $F$에서 $P$를 바라보는 방향과 x축이 이루는 각을 $\theta$라고 둡니다.`,
      String.raw`초점에서 타원 위의 점까지의 거리 공식에 의해 $p = \frac{b^2}{a + c\cos\theta}$, $q = \frac{b^2}{a - c\cos\theta}$입니다.`,
      String.raw`$\frac{q}{p} = 2$이므로 $\frac{a + c\cos\theta}{a - c\cos\theta} = 2$입니다.`,
      String.raw`정리하면 $\cos\theta = \frac{a}{3c}$입니다.`,
      String.raw`$u = \frac{a}{c}$라고 두면 $\frac{p}{c} = \frac{\sqrt{6}}{8}$입니다.`,
      String.raw`또한 $\frac{p}{c} = \frac{u^2 - 1}{u + u/3} = \frac{3(u^2 - 1)}{4u}$입니다.`,
      String.raw`따라서 $\frac{3(u^2 - 1)}{4u} = \frac{\sqrt{6}}{8}$이고, $u = \frac{\sqrt{6}}{2}$입니다.`,
      String.raw`$\cos\theta = \frac{u}{3} = \frac{\sqrt{6}}{6}$이므로 $\sin\theta = \sqrt{\frac{5}{6}}$입니다.`,
      String.raw`삼각형 $FF'Q$의 넓이는 $cq\sin\theta$입니다.`,
      String.raw`$c \times \frac{c\sqrt{6}}{4} \times \sqrt{\frac{5}{6}} = 4\sqrt{5}$이므로 $c^2 = 16$입니다.`,
      String.raw`$b^2 = a^2 - c^2 = c^2(u^2 - 1)$입니다.`,
      String.raw`따라서 $b^2 = 16\left(\frac{6}{4} - 1\right) = 8$입니다.`,
    ],
    commonMistakes: [
      String.raw`$\frac{\overline{PF}}{\overline{QF}}$와 $\frac{\overline{QF}}{\overline{PF}}$를 반대로 읽는 실수입니다.`,
      String.raw`$\overline{FF'} = c$라고 생각하는 실수: 두 초점 사이의 거리는 $2c$입니다.`,
      String.raw`삼각형 $FF'Q$의 넓이를 계산할 때 밑변과 높이를 잘못 잡는 실수입니다.`,
      String.raw`$a^2 = b^2 + c^2$ 관계를 빠뜨리는 실수입니다.`,
      String.raw`$P$와 $Q$가 초점 $F$를 기준으로 반대 방향에 있다는 점을 거리 공식에 반영하지 않는 실수입니다.`,
    ],
  },
];

function practice(
  problem: Omit<PracticeProblem, "printContent">
): PracticeProblem {
  return { ...problem, printContent: problem.content };
}

export const JUNE_MOCK_NEW_PRACTICE_PROBLEMS: PracticeProblem[] = [
  practice({
    id: "common-21-level-1",
    parentId: "common-21",
    level: 1,
    label: "Level 1 · 기본 변형",
    title: "불연속 시점과 극솟점 연결하기",
    description:
      "원문과 같은 구조에서 불연속이 발생하는 시점과 구하려는 함수값을 바꾼 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`최고차항의 계수가 1인 삼차함수 $f(x)$가 있다. 실수 $t$에 대하여 $f(\alpha) = f'(t) - 4t^2 + 4$를 만족시키는 실수 $\alpha$의 최댓값을 $g(t)$라 하자. 함수 $g(t)$가 $t = 2$에서만 불연속이고 $g(2) = 1$일 때, $f(3)$의 값을 구하시오.`,
    answer: "29",
    explanation: [
      String.raw`$f(x) = x^3 + ax^2 + bx + c$로 놓습니다.`,
      String.raw`$H(t) = f'(t) - 4t^2 + 4 = -t^2 + 2at + b + 4$입니다.`,
      String.raw`$g(t)$가 $t = 2$에서만 불연속이므로 $H(t)$의 꼭짓점의 $t$좌표는 2입니다. 따라서 $a = 2$입니다.`,
      String.raw`$g(2) = 1$이므로 $x = 1$은 $f$의 극솟점입니다. 따라서 $f'(1) = 3 + 2a + b = 0$입니다.`,
      String.raw`$a = 2$이므로 $b = -7$입니다.`,
      String.raw`$H(2) = -4 + 8 - 7 + 4 = 1$이고, $H(2) = f(1)$이므로 $1 + 2 - 7 + c = 1$입니다.`,
      String.raw`따라서 $c = 5$입니다.`,
      String.raw`$f(3) = 27 + 18 - 21 + 5 = 29$입니다.`,
      "정답은 29입니다.",
    ],
    difficulty: 3.8,
    tags: ["삼차함수", "극솟값", "불연속", "기본 변형"],
    variationPoint:
      "원문의 구조는 유지하면서 불연속이 발생하는 시점을 t = 3에서 t = 2로 변경했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 공통 21번 기본 변형",
    estimatedSpace: "medium",
  }),
  practice({
    id: "common-21-level-2",
    parentId: "common-21",
    level: 2,
    label: "Level 2 · 구조 변형",
    title: "이차항의 계수가 달라진 조건 해석",
    description:
      "오른쪽 식의 이차항 계수를 바꾸어 꼭짓점 조건을 한 단계 더 주의 깊게 해석하는 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`최고차항의 계수가 1인 삼차함수 $f(x)$가 있다. 실수 $t$에 대하여 $f(\alpha) = f'(t) - 5t^2 + 1$을 만족시키는 실수 $\alpha$의 최댓값을 $g(t)$라 하자. 함수 $g(t)$가 $t = 2$에서만 불연속이고 $g(2) = 1$일 때, $f(3)$의 값을 구하시오.`,
    answer: "34",
    explanation: [
      String.raw`$f(x) = x^3 + ax^2 + bx + c$로 놓습니다.`,
      String.raw`$H(t) = f'(t) - 5t^2 + 1 = -2t^2 + 2at + b + 1$입니다.`,
      String.raw`$H(t)$의 꼭짓점의 $t$좌표는 $\frac{a}{2}$입니다.`,
      String.raw`$g(t)$가 $t = 2$에서만 불연속이므로 $\frac{a}{2} = 2$입니다. 따라서 $a = 4$입니다.`,
      String.raw`$g(2) = 1$이므로 $x = 1$은 $f$의 극솟점입니다.`,
      String.raw`$f'(1) = 3 + 2a + b = 0$이므로 $b = -11$입니다.`,
      String.raw`$H(2) = -8 + 16 - 11 + 1 = -2$입니다.`,
      String.raw`$H(2) = f(1)$이므로 $1 + 4 - 11 + c = -2$입니다. 따라서 $c = 4$입니다.`,
      String.raw`$f(3) = 27 + 36 - 33 + 4 = 34$입니다.`,
      "정답은 34입니다.",
    ],
    difficulty: 4.1,
    tags: ["삼차함수", "극값", "꼭짓점", "구조 변형"],
    variationPoint:
      "H(t)의 이차항 계수가 -1이 아니라 -2가 되도록 바꾸어 꼭짓점의 위치를 계산해야 합니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 공통 21번 구조 변형",
    estimatedSpace: "medium",
  }),
  practice({
    id: "common-21-level-3",
    parentId: "common-21",
    level: 3,
    label: "Level 3 · 심화 변형",
    title: "불연속 조건을 일반화하여 계수 결정하기",
    description:
      "불연속 시점, 극솟점, 오른쪽 식의 계수를 모두 바꾼 심화 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`최고차항의 계수가 1인 삼차함수 $f(x)$가 있다. 실수 $t$에 대하여 $f(\alpha) = f'(t) - 6t^2 + 7$을 만족시키는 실수 $\alpha$의 최댓값을 $g(t)$라 하자. 함수 $g(t)$가 $t = 1$에서만 불연속이고 $g(1) = 2$일 때, $f(4)$의 값을 구하시오.`,
    answer: "30",
    explanation: [
      String.raw`$f(x) = x^3 + ax^2 + bx + c$로 놓습니다.`,
      String.raw`$H(t) = f'(t) - 6t^2 + 7 = -3t^2 + 2at + b + 7$입니다.`,
      String.raw`$H(t)$의 꼭짓점의 $t$좌표는 $\frac{a}{3}$입니다.`,
      String.raw`$g(t)$가 $t = 1$에서만 불연속이므로 $\frac{a}{3} = 1$입니다. 따라서 $a = 3$입니다.`,
      String.raw`$g(1) = 2$이므로 $x = 2$는 $f$의 극솟점입니다.`,
      String.raw`$f'(2) = 12 + 4a + b = 0$이므로 $b = -24$입니다.`,
      String.raw`$H(1) = -3 + 6 - 24 + 7 = -14$입니다.`,
      String.raw`$H(1) = f(2)$이므로 $8 + 12 - 48 + c = -14$입니다. 따라서 $c = 14$입니다.`,
      String.raw`$f(4) = 64 + 48 - 96 + 14 = 30$입니다.`,
      "정답은 30입니다.",
    ],
    difficulty: 4.5,
    tags: ["삼차함수", "불연속", "극솟점", "심화 변형"],
    variationPoint:
      "극솟점이 x = 1이 아닌 x = 2가 되도록 바꾸고, H(t)의 꼭짓점 조건도 함께 일반화했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 공통 21번 심화 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "probability-28-level-1",
    parentId: "probability-28",
    level: 1,
    label: "Level 1 · 기본 변형",
    title: "두 번의 시행으로 상태 복원하기",
    description:
      "반복 횟수를 줄여 뒤집기 집합의 조합을 직접 확인하는 기본 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`앞면과 뒷면에 각각 숫자 1, 2, 3, 4, 5, 6이 하나씩 적힌 카드 6장이 있다. 처음에 숫자 1과 6이 적힌 카드는 뒷면이 보이도록 놓여 있고, 나머지 카드는 앞면이 보이도록 놓여 있다. 주사위를 한 번 던져 나온 눈의 수가 $k$일 때, $k$가 홀수이면 $k$ 이하의 수가 적힌 카드를 모두 한 번씩 뒤집고, $k$가 짝수이면 $k$ 이상의 수가 적힌 카드를 모두 한 번씩 뒤집는다. 이 시행을 2번 반복한 후 모든 카드가 앞면이 보이도록 놓여 있을 확률은 $\frac{p}{q}$이다. $p$와 $q$가 서로소인 자연수일 때, $p + q$의 값을 구하시오.`,
    answer: "10",
    explanation: [
      String.raw`처음 뒷면인 카드의 집합은 $\{1, 6\}$입니다.`,
      String.raw`두 번의 시행으로 $\{1, 6\}$을 뒤집어야 모든 카드가 앞면이 됩니다.`,
      String.raw`가능한 주사위 눈의 순서쌍은 $(1, 6)$, $(6, 1)$, $(2, 5)$, $(5, 2)$입니다.`,
      String.raw`유리한 경우는 4가지이고 전체 경우는 $6^2 = 36$가지입니다.`,
      String.raw`확률은 $\frac{4}{36} = \frac{1}{9}$입니다.`,
      String.raw`따라서 $p + q = 1 + 9 = 10$입니다.`,
      "정답은 10입니다.",
    ],
    difficulty: 3.2,
    tags: ["확률", "카드 뒤집기", "대칭차", "기본 변형"],
    variationPoint:
      "원문의 시행 횟수를 네 번에서 두 번으로 줄여 상태 전이의 기본 원리를 직접 확인할 수 있도록 했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 확률과 통계 28번 기본 변형",
    estimatedSpace: "medium",
  }),
  practice({
    id: "probability-28-level-2",
    parentId: "probability-28",
    level: 2,
    label: "Level 2 · 구조 변형",
    title: "세 번 시행의 순서쌍 개수 세기",
    description:
      "초기 상태와 반복 횟수를 바꾸어 상태 전이표를 활용하는 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`앞면과 뒷면에 각각 숫자 1, 2, 3, 4, 5, 6이 하나씩 적힌 카드 6장이 있다. 처음에 숫자 1, 4, 5가 적힌 카드는 뒷면이 보이도록 놓여 있고, 나머지 카드는 앞면이 보이도록 놓여 있다. 주사위를 한 번 던져 나온 눈의 수가 $k$일 때, $k$가 홀수이면 $k$ 이하의 수가 적힌 카드를 모두 한 번씩 뒤집고, $k$가 짝수이면 $k$ 이상의 수가 적힌 카드를 모두 한 번씩 뒤집는다. 이 시행을 3번 반복한다. 주사위를 던져 나온 눈의 수를 차례대로 $k_1$, $k_2$, $k_3$이라 할 때, 모든 카드가 앞면이 되도록 하는 순서쌍 $(k_1, k_2, k_3)$의 개수를 구하시오.`,
    answer: "24",
    explanation: [
      String.raw`처음 뒷면인 카드의 집합은 $T = \{1, 4, 5\}$입니다.`,
      "첫 두 번 시행의 대칭차 상태를 먼저 정리합니다.",
      String.raw`세 번째 주사위 눈이 1일 때 첫 두 번 시행의 대칭차는 $\{4, 5\}$여야 하며, 이를 만드는 순서는 4가지입니다.`,
      String.raw`세 번째 주사위 눈이 2일 때 첫 두 번 시행의 대칭차는 $\{1, 2, 3, 6\}$이어야 하며, 이를 만드는 순서는 4가지입니다.`,
      String.raw`세 번째 주사위 눈이 3일 때 필요한 상태는 $\{2, 3, 4, 5\}$이고, 가능한 순서는 4가지입니다.`,
      String.raw`세 번째 주사위 눈이 4일 때 필요한 상태는 $\{1, 6\}$이고, 가능한 순서는 4가지입니다.`,
      String.raw`세 번째 주사위 눈이 5일 때 필요한 상태는 $\{2, 3\}$이고, 가능한 순서는 4가지입니다.`,
      String.raw`세 번째 주사위 눈이 6일 때 필요한 상태는 $\{1, 4, 5, 6\}$이고, 가능한 순서는 4가지입니다.`,
      String.raw`따라서 전체 순서쌍의 개수는 $4 + 4 + 4 + 4 + 4 + 4 = 24$입니다.`,
      "정답은 24입니다.",
    ],
    difficulty: 3.9,
    tags: ["확률과 통계", "상태 전이", "대칭차", "구조 변형"],
    variationPoint:
      "초기 뒷면 카드의 집합을 {1, 4, 5}로 바꾸고, 세 번 시행의 순서쌍 개수를 직접 묻습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 확률과 통계 28번 구조 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "probability-28-level-3",
    parentId: "probability-28",
    level: 3,
    label: "Level 3 · 심화 변형",
    title: "모든 카드가 뒷면인 상태에서 출발하기",
    description:
      "초기 상태를 크게 바꾸고 두 번 시행의 결과를 결합하여 계산하는 심화 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`앞면과 뒷면에 각각 숫자 1, 2, 3, 4, 5, 6이 하나씩 적힌 카드 6장이 있다. 처음에는 6장의 카드가 모두 뒷면이 보이도록 놓여 있다. 주사위를 한 번 던져 나온 눈의 수가 $k$일 때, $k$가 홀수이면 $k$ 이하의 수가 적힌 카드를 모두 한 번씩 뒤집고, $k$가 짝수이면 $k$ 이상의 수가 적힌 카드를 모두 한 번씩 뒤집는다. 이 시행을 4번 반복한 후 모든 카드가 앞면이 보이도록 놓여 있을 확률은 $\frac{p}{q}$이다. $p$와 $q$가 서로소인 자연수일 때, $p + q$의 값을 구하시오.`,
    answer: "61",
    explanation: [
      "처음에는 모든 카드가 뒷면이므로 네 번의 시행을 합성한 뒤 모든 카드가 한 번씩 뒤집힌 상태가 되어야 합니다.",
      "두 번의 시행 결과를 먼저 셉니다.",
      "아무 카드도 뒤집히지 않은 상태는 같은 주사위 눈이 두 번 나오는 6가지 순서로 만들어집니다.",
      "모든 카드가 뒤집힌 상태도 6가지 순서로 만들어집니다.",
      "나머지 여섯 종류의 상태는 각각 4가지 순서로 만들어집니다.",
      "네 번 시행의 결과가 전체 카드 집합이 되려면 앞의 두 시행 결과와 뒤의 두 시행 결과가 서로 전체 집합 기준으로 보완 관계여야 합니다.",
      String.raw`아무 카드도 뒤집히지 않은 상태와 전체 카드 상태가 결합되는 경우는 $6 \times 6 + 6 \times 6 = 72$가지입니다.`,
      String.raw`나머지 여섯 상태는 각각 자신의 보완 상태와 결합하며, 각 경우의 수는 $4 \times 4$입니다.`,
      String.raw`따라서 유리한 경우의 수는 $72 + 6 \times 16 = 168$입니다.`,
      String.raw`전체 경우의 수는 $6^4 = 1296$입니다.`,
      String.raw`확률은 $\frac{168}{1296} = \frac{7}{54}$입니다.`,
      String.raw`따라서 $p + q = 7 + 54 = 61$입니다.`,
      "정답은 61입니다.",
    ],
    difficulty: 4.4,
    tags: ["확률", "상태 전이", "대칭차", "심화 변형"],
    variationPoint:
      "초기 상태를 모든 카드가 뒷면인 경우로 바꾸어 두 시행 묶음의 결합을 더 정교하게 계산하도록 했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 확률과 통계 28번 심화 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "calculus-28-level-1",
    parentId: "calculus-28",
    level: 1,
    label: "Level 1 · 기본 변형",
    title: "지수함수 관계식을 이용한 기본 미분",
    description:
      "지수의 비율을 단순화하여 관계식과 이계도함수 계산의 기본 흐름을 익히는 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`좌표평면에서 양수 $t$에 대하여 직선 $y = t$가 두 곡선 $y = e^x - e^{-x} + 1$, $y = e^x$와 만나는 점을 각각 $P$, $Q$라 하자. 점 $P$를 지나고 x축에 수직인 직선이 곡선 $y = e^x$와 만나는 점의 y좌표를 $f(t)$, 점 $Q$를 지나고 x축에 수직인 직선이 곡선 $y = e^x - e^{-x} + 1$과 만나는 점의 y좌표를 $g(t)$라 하자. 두 함수 $f(t)$, $g(t)$는 구간 $(0, \infty)$에서 미분가능한 함수이다. $\displaystyle \lim_{t \to 1} \frac{4f'(t) - g'(t)}{t - 1}$의 값을 구하시오.`,
    answer: "3",
    explanation: [
      String.raw`$f(t) = u$라고 놓으면 점 $P$의 조건에서 $t = u - \frac{1}{u} + 1$입니다.`,
      String.raw`$t = 1$일 때 $u = 1$입니다.`,
      String.raw`양변을 미분하면 $1 = f'(t)\left(1 + \frac{1}{(f(t))^2}\right)$입니다.`,
      String.raw`따라서 $f'(1) = \frac{1}{2}$입니다.`,
      String.raw`한 번 더 미분하면 $f''(1) = \frac{1}{4}$입니다.`,
      String.raw`점 $Q$의 조건에서 $g(t) = t - \frac{1}{t} + 1$입니다.`,
      String.raw`따라서 $g'(1) = 2$이고 $g''(1) = -2$입니다.`,
      String.raw`$4f'(1) - g'(1) = 0$이므로 구하려는 극한은 $4f''(1) - g''(1)$입니다.`,
      String.raw`$4 \times \frac{1}{4} - (-2) = 3$입니다.`,
      "정답은 3입니다.",
    ],
    difficulty: 3.6,
    tags: ["미적분", "음함수 미분", "극한", "기본 변형"],
    variationPoint:
      "원문의 지수 e^{2x}와 e^{-x}를 e^x와 e^{-x}로 단순화하여 핵심 관계식에 집중하도록 했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 미적분 28번 기본 변형",
    estimatedSpace: "medium",
  }),
  practice({
    id: "calculus-28-level-2",
    parentId: "calculus-28",
    level: 2,
    label: "Level 2 · 구조 변형",
    title: "지수의 비율을 바꾸어 계산하기",
    description:
      "지수의 비율이 달라졌을 때 관계식의 거듭제곱을 정확히 해석하는 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`좌표평면에서 양수 $t$에 대하여 직선 $y = t$가 두 곡선 $y = e^{3x} - e^{-x} + 1$, $y = e^{3x}$와 만나는 점을 각각 $P$, $Q$라 하자. 점 $P$를 지나고 x축에 수직인 직선이 곡선 $y = e^{3x}$와 만나는 점의 y좌표를 $f(t)$, 점 $Q$를 지나고 x축에 수직인 직선이 곡선 $y = e^{3x} - e^{-x} + 1$과 만나는 점의 y좌표를 $g(t)$라 하자. 두 함수 $f(t)$, $g(t)$는 구간 $(0, \infty)$에서 미분가능한 함수이다. $\displaystyle \lim_{t \to 1} \frac{16f'(t) - 9g'(t)}{t - 1}$의 값을 구하시오.`,
    answer: "7",
    explanation: [
      String.raw`$f(t) = u$라고 놓습니다.`,
      String.raw`점 $P$의 조건에서 $t = u - u^{-1/3} + 1$입니다.`,
      String.raw`$t = 1$일 때 $u = 1$입니다.`,
      String.raw`양변을 미분하면 $1 = f'(t)\left(1 + \frac{1}{3}(f(t))^{-4/3}\right)$입니다.`,
      String.raw`따라서 $f'(1) = \frac{3}{4}$입니다.`,
      String.raw`한 번 더 미분하면 $f''(1) = \frac{3}{16}$입니다.`,
      String.raw`점 $Q$의 조건에서 $g(t) = t - t^{-1/3} + 1$입니다.`,
      String.raw`따라서 $g'(1) = \frac{4}{3}$이고 $g''(1) = -\frac{4}{9}$입니다.`,
      String.raw`$16f'(1) - 9g'(1) = 12 - 12 = 0$입니다.`,
      String.raw`구하려는 극한은 $16f''(1) - 9g''(1)$입니다.`,
      String.raw`$16 \times \frac{3}{16} - 9 \times \left(-\frac{4}{9}\right) = 3 + 4 = 7$입니다.`,
      "정답은 7입니다.",
    ],
    difficulty: 4.0,
    tags: ["지수함수", "음함수 미분", "극한", "구조 변형"],
    variationPoint:
      "e^{3x}와 e^{-x}를 사용하여 f(t)의 관계식에 세제곱근이 나타나도록 바꾸었습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 미적분 28번 구조 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "calculus-28-level-3",
    parentId: "calculus-28",
    level: 3,
    label: "Level 3 · 심화 변형",
    title: "계수와 상수항이 달라진 관계식 미분",
    description:
      "지수함수 앞의 계수와 상수항까지 바뀐 상황에서 관계식을 정확히 구성하는 심화 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`좌표평면에서 양수 $t$에 대하여 직선 $y = t$가 두 곡선 $y = e^{2x} - 2e^{-2x} + 2$, $y = e^{2x}$와 만나는 점을 각각 $P$, $Q$라 하자. 점 $P$를 지나고 x축에 수직인 직선이 곡선 $y = e^{2x}$와 만나는 점의 y좌표를 $f(t)$, 점 $Q$를 지나고 x축에 수직인 직선이 곡선 $y = e^{2x} - 2e^{-2x} + 2$와 만나는 점의 y좌표를 $g(t)$라 하자. 두 함수 $f(t)$, $g(t)$는 구간 $(0, \infty)$에서 미분가능한 함수이다. $\displaystyle \lim_{t \to 1} \frac{27f'(t) - 3g'(t)}{t - 1}$의 값을 구하시오.`,
    answer: "16",
    explanation: [
      String.raw`$f(t) = u$라고 놓습니다.`,
      String.raw`점 $P$의 조건에서 $t = u - \frac{2}{u} + 2$입니다.`,
      String.raw`$t = 1$일 때 $u = 1$입니다.`,
      String.raw`양변을 미분하면 $1 = f'(t)\left(1 + \frac{2}{(f(t))^2}\right)$입니다.`,
      String.raw`따라서 $f'(1) = \frac{1}{3}$입니다.`,
      String.raw`한 번 더 미분하면 $f''(1) = \frac{4}{27}$입니다.`,
      String.raw`점 $Q$의 조건에서 $g(t) = t - \frac{2}{t} + 2$입니다.`,
      String.raw`따라서 $g'(1) = 3$이고 $g''(1) = -4$입니다.`,
      String.raw`$27f'(1) - 3g'(1) = 9 - 9 = 0$입니다.`,
      String.raw`구하려는 극한은 $27f''(1) - 3g''(1)$입니다.`,
      String.raw`$27 \times \frac{4}{27} - 3 \times (-4) = 4 + 12 = 16$입니다.`,
      "정답은 16입니다.",
    ],
    difficulty: 4.4,
    tags: ["미적분", "음함수 미분", "이계도함수", "심화 변형"],
    variationPoint:
      "감산되는 지수함수 앞에 계수 2를 추가하고 상수항을 조정하여 관계식의 미분 계산을 확장했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 미적분 28번 심화 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "geometry-28-level-1",
    parentId: "geometry-28",
    level: 1,
    label: "Level 1 · 기본 변형",
    title: "거리비와 넓이로 단축 구하기",
    description:
      "원문의 거리비 구조를 유지하면서 수치를 바꾼 기본 변형 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`두 초점이 $F(c, 0)$, $F'(-c, 0)$ ($c > 0$)인 타원 $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$이 있다. 이 타원 위에 있는 제1사분면 위의 점 $P$와 제4사분면 위의 점 $Q$에 대하여 점 $F$가 선분 $PQ$ 위에 있고 $\frac{\overline{PF}}{\overline{QF}} = \frac{1}{2}$, $\frac{\overline{PF}}{\overline{FF'}} = \frac{5}{16}$이다. 삼각형 $FF'Q$의 넓이가 $5\sqrt{3}$일 때, $b^2$의 값을 구하시오.`,
    answer: "10",
    explanation: [
      String.raw`$p = \overline{PF}$, $q = \overline{QF}$라고 두면 $q = 2p$입니다.`,
      String.raw`$\frac{\overline{PF}}{\overline{FF'}} = \frac{5}{16}$이고 $\overline{FF'} = 2c$이므로 $p = \frac{5c}{8}$, $q = \frac{5c}{4}$입니다.`,
      String.raw`점 $F$에서 $P$를 바라보는 방향과 x축이 이루는 각을 $\theta$라고 둡니다.`,
      String.raw`$\frac{q}{p} = 2$이므로 $\frac{a + c\cos\theta}{a - c\cos\theta} = 2$입니다.`,
      String.raw`따라서 $\cos\theta = \frac{a}{3c}$입니다.`,
      String.raw`$u = \frac{a}{c}$라고 두면 $\frac{p}{c} = \frac{5}{8}$입니다.`,
      String.raw`또한 $\frac{p}{c} = \frac{3(u^2 - 1)}{4u}$이므로 $\frac{3(u^2 - 1)}{4u} = \frac{5}{8}$입니다.`,
      String.raw`이를 풀면 $u = \frac{3}{2}$입니다.`,
      String.raw`따라서 $\sin\theta = \sqrt{1 - (u/3)^2} = \frac{\sqrt{3}}{2}$입니다.`,
      String.raw`삼각형의 넓이는 $c \times \frac{5c}{4} \times \frac{\sqrt{3}}{2}$입니다.`,
      String.raw`이 값이 $5\sqrt{3}$이므로 $c^2 = 8$입니다.`,
      String.raw`$b^2 = c^2(u^2 - 1) = 8\left(\frac{9}{4} - 1\right) = 10$입니다.`,
      "정답은 10입니다.",
    ],
    difficulty: 3.7,
    tags: ["기하", "타원", "초점", "기본 변형"],
    variationPoint:
      "원문의 거리비는 유지하고 PF/FF'와 넓이를 바꾸어 같은 풀이 흐름을 연습하도록 했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 기하 28번 기본 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "geometry-28-level-2",
    parentId: "geometry-28",
    level: 2,
    label: "Level 2 · 구조 변형",
    title: "거리비가 달라진 초점 현 분석",
    description:
      "PF와 QF의 비율을 바꾸어 초점 현 공식의 일반적인 사용법을 익히는 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`두 초점이 $F(c, 0)$, $F'(-c, 0)$ ($c > 0$)인 타원 $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$이 있다. 이 타원 위에 있는 제1사분면 위의 점 $P$와 제4사분면 위의 점 $Q$에 대하여 점 $F$가 선분 $PQ$ 위에 있고 $\frac{\overline{PF}}{\overline{QF}} = \frac{1}{3}$, $\frac{\overline{PF}}{\overline{FF'}} = \frac{2\sqrt{3}}{9}$이다. 삼각형 $FF'Q$의 넓이가 $6\sqrt{3}$일 때, $b^2$의 값을 구하시오.`,
    answer: "18",
    explanation: [
      String.raw`$p = \overline{PF}$, $q = \overline{QF}$라고 두면 $q = 3p$입니다.`,
      String.raw`$\frac{\overline{PF}}{\overline{FF'}} = \frac{2\sqrt{3}}{9}$이고 $\overline{FF'} = 2c$이므로 $p = \frac{4c\sqrt{3}}{9}$입니다.`,
      String.raw`따라서 $q = \frac{4c\sqrt{3}}{3}$입니다.`,
      String.raw`$\frac{q}{p} = 3$이므로 $\frac{a + c\cos\theta}{a - c\cos\theta} = 3$입니다.`,
      String.raw`정리하면 $\cos\theta = \frac{a}{2c}$입니다.`,
      String.raw`$u = \frac{a}{c}$라고 두면 $\frac{p}{c} = \frac{4\sqrt{3}}{9}$입니다.`,
      String.raw`또한 $\frac{p}{c} = \frac{u^2 - 1}{u + u/2} = \frac{2(u^2 - 1)}{3u}$입니다.`,
      String.raw`$\frac{2(u^2 - 1)}{3u} = \frac{4\sqrt{3}}{9}$를 풀면 $u = \sqrt{3}$입니다.`,
      String.raw`따라서 $\sin\theta = \sqrt{1 - (u/2)^2} = \frac{1}{2}$입니다.`,
      String.raw`삼각형의 넓이는 $c \times \frac{4c\sqrt{3}}{3} \times \frac{1}{2}$입니다.`,
      String.raw`이 값이 $6\sqrt{3}$이므로 $c^2 = 9$입니다.`,
      String.raw`$b^2 = c^2(u^2 - 1) = 9(3 - 1) = 18$입니다.`,
      "정답은 18입니다.",
    ],
    difficulty: 4.1,
    tags: ["타원", "초점 현", "거리비", "구조 변형"],
    variationPoint:
      "PF/QF를 1/3으로 바꾸어 cosθ와 a/c의 관계를 새로 유도해야 합니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 기하 28번 구조 변형",
    estimatedSpace: "large",
  }),
  practice({
    id: "geometry-28-level-3",
    parentId: "geometry-28",
    level: 3,
    label: "Level 3 · 심화 변형",
    title: "거리비 1 대 4인 초점 현 추적",
    description:
      "거리비를 확장하여 초점 현 공식과 넓이 조건을 정교하게 결합하는 심화 문제입니다.",
    questionType: "short-answer",
    status: "published",
    content: String.raw`두 초점이 $F(c, 0)$, $F'(-c, 0)$ ($c > 0$)인 타원 $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$이 있다. 이 타원 위에 있는 제1사분면 위의 점 $P$와 제4사분면 위의 점 $Q$에 대하여 점 $F$가 선분 $PQ$ 위에 있고 $\frac{\overline{PF}}{\overline{QF}} = \frac{1}{4}$, $\frac{\overline{PF}}{\overline{FF'}} = \frac{9}{64}$이다. 삼각형 $FF'Q$의 넓이가 $18\sqrt{7}$일 때, $b^2$의 값을 구하시오.`,
    answer: "36",
    explanation: [
      String.raw`$p = \overline{PF}$, $q = \overline{QF}$라고 두면 $q = 4p$입니다.`,
      String.raw`$\frac{\overline{PF}}{\overline{FF'}} = \frac{9}{64}$이고 $\overline{FF'} = 2c$이므로 $p = \frac{9c}{32}$입니다.`,
      String.raw`따라서 $q = \frac{9c}{8}$입니다.`,
      String.raw`$\frac{q}{p} = 4$이므로 $\frac{a + c\cos\theta}{a - c\cos\theta} = 4$입니다.`,
      String.raw`정리하면 $\cos\theta = \frac{3a}{5c}$입니다.`,
      String.raw`$u = \frac{a}{c}$라고 두면 $\frac{p}{c} = \frac{9}{32}$입니다.`,
      String.raw`또한 $\frac{p}{c} = \frac{u^2 - 1}{u + 3u/5} = \frac{5(u^2 - 1)}{8u}$입니다.`,
      String.raw`$\frac{5(u^2 - 1)}{8u} = \frac{9}{32}$를 풀면 $u = \frac{5}{4}$입니다.`,
      String.raw`따라서 $\sin\theta = \sqrt{1 - (3u/5)^2} = \frac{\sqrt{7}}{4}$입니다.`,
      String.raw`삼각형의 넓이는 $c \times \frac{9c}{8} \times \frac{\sqrt{7}}{4}$입니다.`,
      String.raw`이 값이 $18\sqrt{7}$이므로 $c^2 = 64$입니다.`,
      String.raw`$b^2 = c^2(u^2 - 1) = 64\left(\frac{25}{16} - 1\right) = 36$입니다.`,
      "정답은 36입니다.",
    ],
    difficulty: 4.5,
    tags: ["기하", "타원", "초점 현", "심화 변형"],
    variationPoint:
      "PF/QF를 1/4로 확장하여 거리비에서 각도 조건을 유도하고 넓이까지 연결하도록 했습니다.",
    printAnswerLine: true,
    sourceLabel: "2027학년도 6월 모평 기하 28번 심화 변형",
    estimatedSpace: "large",
  }),
];
